-- Migration: 005_contracts_form_data_and_pdf.sql
-- Add columns to contracts for form data, generated/signed PDFs, and status.

ALTER TABLE contracts ADD COLUMN IF NOT EXISTS form_data JSONB;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS contract_type VARCHAR(50);
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS pdf_generated BYTEA;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS pdf_signed BYTEA;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending';

-- Backfill status from signed_at where applicable
UPDATE contracts SET status = 'signed' WHERE signed_at IS NOT NULL AND (status IS NULL OR status = '');
UPDATE contracts SET status = 'pending' WHERE status IS NULL OR status = '';
